/**
 * Build-time helper: inlines the built web UI (web/dist) into a generated
 * TypeScript module (server/src/embedded-web.ts) so the SEA/npm bundle ships
 * the UI inside the executable — no web/ folder needed next to the .exe.
 *
 * Each file becomes { b64, type } keyed by its URL path (e.g. "/assets/x.js").
 * The server serves these from memory, which also sidesteps the
 * application/octet-stream MIME bug that happened when the Vite *source*
 * index.html was served instead of the production build.
 */
import { readdir, readFile, stat, writeFile, mkdir } from "node:fs/promises";
import { join, relative, sep } from "node:path";

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".eot": "application/vnd.ms-fontobject",
  ".map": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
};

function mimeFor(file) {
  const dot = file.lastIndexOf(".");
  if (dot >= 0) {
    const t = MIME[file.slice(dot).toLowerCase()];
    if (t) return t;
  }
  return "application/octet-stream";
}

async function walk(dir, base, out) {
  for (const entry of await readdir(dir)) {
    const abs = join(dir, entry);
    const s = await stat(abs);
    if (s.isDirectory()) {
      await walk(abs, base, out);
    } else {
      const rel = relative(base, abs).split(sep).join("/");
      const url = "/" + rel;
      const buf = await readFile(abs);
      out[url] = { b64: buf.toString("base64"), type: mimeFor(entry) };
    }
  }
}

export async function generateEmbeddedWeb(webDist, outFile) {
  const map = {};
  await walk(webDist, webDist, map);
  const count = Object.keys(map).length;
  const lines = [
    "// GENERATED by cli/scripts/embed-web.mjs — do not edit.",
    "// Inlined production web UI (web/dist). Consumed by server/src/index.ts",
    "// when present, making the SEA/npm bundle self-contained.",
    "export interface EmbeddedAsset { b64: string; type: string; }",
    "export const EMBEDDED_WEB: Record<string, EmbeddedAsset> = {",
    ...Object.entries(map).map(([url, a]) => `  ${JSON.stringify(url)}: { b64: ${JSON.stringify(a.b64)}, type: ${JSON.stringify(a.type)} },`),
    "};",
    "",
  ];
  await mkdir(join(outFile, ".."), { recursive: true });
  await writeFile(outFile, lines.join("\n"), "utf-8");
  return count;
}

/**
 * Writes an empty EMBEDDED_WEB map. Used in server-only / embed mode
 * (BUILD_EMBED_WEB=0): the bundle then serves the UI from a web/ folder on
 * disk (fastifyStatic fallback in server/src/index.ts) instead of inlining it.
 */
export async function writeEmptyEmbeddedWeb(outFile) {
  const lines = [
    "// GENERATED by cli/scripts/embed-web.mjs — do not edit.",
    "// Empty by design (BUILD_EMBED_WEB=0): the server serves the UI from a",
    "// web/ folder on disk via fastifyStatic, not from this map.",
    "export interface EmbeddedAsset { b64: string; type: string; }",
    "export const EMBEDDED_WEB: Record<string, EmbeddedAsset> = {};",
    "",
  ];
  await mkdir(join(outFile, ".."), { recursive: true });
  await writeFile(outFile, lines.join("\n"), "utf-8");
}
